# Stage 1: Build env
FROM debian:12-slim as build

ARG DATA_YEAR=2025
ENV DATA_YEAR=${DATA_YEAR}

# Non-interactive config for tzdata install
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
RUN apt-get update && apt-get install -y tzdata
RUN dpkg-reconfigure --frontend noninteractive tzdata  # Optional; sets to UTC

RUN apt-get update && \
    apt-get install -y awscli unzip sqlite3 sudo build-essential wget curl git ruby make

WORKDIR /workspace
COPY . .

RUN chmod +x build/tiger_import build/build_indexes build/rebuild_cluster bin/rebuild_metaphones

RUN mkdir -p ./tiger_data/
RUN aws s3 sync s3://choa-geocoding/census/tiger_line/${DATA_YEAR}/ ./tiger_data/ \
    --exclude "*" \
    --include "*addr.zip" \
    --include "*edges.zip" \
    --include "*featnames.zip"

RUN find ./tiger_data -name "*.zip" -exec unzip -d ./TIGER${DATA_YEAR} {} \;

RUN sudo build/tiger_import /opt/geocoder.db TIGER${DATA_YEAR}
RUN sudo rm -r TIGER${DATA_YEAR}
RUN sudo bin/rebuild_metaphones /opt/geocoder.db
RUN sudo chmod +x build/build_indexes && sudo build/build_indexes /opt/geocoder.db
RUN sudo chmod +x build/rebuild_cluster && sudo build/rebuild_cluster /opt/geocoder.db

# Stage 2: minimal image with only the result
FROM debian:12-slim as final
COPY --from=build /opt/geocoder.db /geocoder.db

CMD ["bash"]